"""empty message

Revision ID: 25321c5813a4
Revises: ac3dde0304f1
Create Date: 2023-10-25 22:09:38.100159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25321c5813a4'
down_revision = 'ac3dde0304f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('height',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
